# Generated by Django 2.0.3 on 2018-03-22 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_yadt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image', django_yadt.fields.YADTImageField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_hash', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-created',),
            },
        ),
    ]
