INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.postgres',
    'django.contrib.staticfiles',

    'django_keyerror',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'email_from_template',
    'formtools',
    'markdown_deux',
    'staticfiles_dotd',
    'switch_templatetag',
    'two_factor',

    'freenodejobs.account',
    'freenodejobs.account.account_reset_password',
    'freenodejobs.account.account_two_factor_auth',
    'freenodejobs.admin',
    'freenodejobs.dashboard',
    'freenodejobs.jobs',
    'freenodejobs.jobs.jobs_add_edit',
    'freenodejobs.jobs.jobs_state_history',
    'freenodejobs.profile',
    'freenodejobs.registration',
    'freenodejobs.static',
    'freenodejobs.utils',
    'freenodejobs.utils.templatetags',
)
