# Generated by Django 2.0.4 on 2018-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_tags', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, through='jobs_tags.JobTag', to='jobs_tags.Tag'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
    ]
