# Generated by Django 2.0.5 on 2018-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180412_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True),
        ),
    ]
