# Generated by Django 2.0.5 on 2018-06-05 21:35

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    User = apps.get_model('account', 'User')

    for x in User.objects.all():
        x.email_validated = x.date_joined
        x.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
